version = 1

[envs.deven]
channels = ["conda-forge"]

[envs.deven.dependencies]
fish = "*"
"fd-find" = "*"
eza = "*"
ripgrep = "*"
zoxide = "*"
yazi = "*"
pixi-pack = "*"
tmux = "*"
nvim = "*"
glow-md = "*"
bat = "*"
lua = "*"
luarocks = "*"

[envs.deven.exposed]
fish = "fish"
fish_indent = "fish_indent"
fish_key_reader = "fish_key_reader"
bat = "bat"
nvim = "nvim"
fd = "fd"
eza = "eza"
rg = "rg"
zoxide = "zoxide"
ya = "ya"
yazi = "yazi"
pixi-pack = "pixi-pack"
