version = 1

[envs.deven]
channels = ["conda-forge", "bioconda"]

[envs.deven.dependencies]
zsh = "*"
"fd-find" = "*"
eza = "*"
ripgrep = "*"
zoxide = "*"
pixi-pack = "*"
tmux = "*"
nvim = "*"
glow-md = "*"
bat = "*"
lua = "*"
luarocks = "*"
uv = "*"
python = "3.8.*"
ruff = "*"
fzf = "*"

[envs.deven.exposed]
zsh = "zsh"
bat = "bat"
nvim = "nvim"
fd = "fd"
eza = "eza"
rg = "rg"
zoxide = "zoxide"
pixi-pack = "pixi-pack"
