# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
# sudo nano ~/.tmux.conf
# ~/.tmux/plugins/tpm/bin/install_plugins
#
# sudo nano ~/.config/gtk-3.0/gtk.css
# VteTerminal,
# vte-terminal,
# TerminalScreen {
#  padding: 0px;
#  margin: 0px;
#  -VteTerminal-inner-border: 0px;
# }

set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins"

# Enable mouse mode
set -g mouse on

# Enable vi mode in copy mode
setw -g mode-keys vi

# Use vim-style split window commands
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes with vim keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Easier access to copy mode
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection-and-cancel

# List of plugins
set -g @tpm_plugins '                   \
    tmux-plugins/tpm                    \
    tmux-plugins/tmux-sensible          \
    tmux-plugins/tmux-resurrect         \
    tmux-plugins/tmux-continuum         \
'

# Initialize TPM (tmux plugin manager)
run '~/.tmux/plugins/tpm/tpm'

