# /etc/nix/nix.conf

experimental-features = nix-command flakes
build-users-group = nixbld
max-jobs = auto
cores = 0
trusted-substituters = https://cache.nixos.org/
keep-outputs = false
keep-derivations = false
auto-optimise-store = true
gc-reserved-space = 5G

